name: "Build"
on:
  push:
    branches:
      - autobuild
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          target: target 

      - name: "Upload Artifact"
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
